// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: math.proto

#include "math.pb.h"
#include "math.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace math {

static const char* MathServices_method_names[] = {
  "/math.MathServices/computeSum",
};

std::unique_ptr< MathServices::Stub> MathServices::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MathServices::Stub> stub(new MathServices::Stub(channel, options));
  return stub;
}

MathServices::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_computeSum_(MathServices_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MathServices::Stub::computeSum(::grpc::ClientContext* context, const ::math::SumOperand& request, ::math::SumResult* response) {
  return ::grpc::internal::BlockingUnaryCall< ::math::SumOperand, ::math::SumResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_computeSum_, context, request, response);
}

void MathServices::Stub::async::computeSum(::grpc::ClientContext* context, const ::math::SumOperand* request, ::math::SumResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::math::SumOperand, ::math::SumResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_computeSum_, context, request, response, std::move(f));
}

void MathServices::Stub::async::computeSum(::grpc::ClientContext* context, const ::math::SumOperand* request, ::math::SumResult* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_computeSum_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::math::SumResult>* MathServices::Stub::PrepareAsynccomputeSumRaw(::grpc::ClientContext* context, const ::math::SumOperand& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::math::SumResult, ::math::SumOperand, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_computeSum_, context, request);
}

::grpc::ClientAsyncResponseReader< ::math::SumResult>* MathServices::Stub::AsynccomputeSumRaw(::grpc::ClientContext* context, const ::math::SumOperand& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynccomputeSumRaw(context, request, cq);
  result->StartCall();
  return result;
}

MathServices::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MathServices_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MathServices::Service, ::math::SumOperand, ::math::SumResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MathServices::Service* service,
             ::grpc::ServerContext* ctx,
             const ::math::SumOperand* req,
             ::math::SumResult* resp) {
               return service->computeSum(ctx, req, resp);
             }, this)));
}

MathServices::Service::~Service() {
}

::grpc::Status MathServices::Service::computeSum(::grpc::ServerContext* context, const ::math::SumOperand* request, ::math::SumResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace math

